# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_remove_cart_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=8.88, max_digits=50),
            preserve_default=False,
        ),
    ]
