# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20160223_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_total_price',
            field=models.DecimalField(decimal_places=2, default=7.99, max_digits=50, null=True),
        ),
    ]
